spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: bsnuser
    password: bsn1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database_platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: P7j94E6bNNVTF4crNoyxVwVEIaWohejnv0PLbU7NJxwxGnDKQJrsMQ3HbBpzeXUW
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account