spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: bsnuser
    password: bsn1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database_platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: account@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
application:
  security:
    jwt:
      secret-key: P7j94E6bNNVTF4crNoyxVwVEIaWohejnv0PLbU7NJxwxGnDKQJrsMQ3HbBpzeXUW
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ../uploads
server:
  port: 8088